/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.presentation;

import util.Navigation;

/**
 *
 * @author GEORGE
 */
public class FrameMain extends javax.swing.JFrame {

    private PanelMain panelMain = new PanelMain();
    private PanelDataCNatural dataCNatural = new PanelDataCNatural();
    private PanelDataCJuridicos dataCJuridicos = new PanelDataCJuridicos();
    private PanelRegistroCNatural registroCNatural = new PanelRegistroCNatural();
    private PanelRegistroJuridico registroJuridico = new PanelRegistroJuridico();
    private PanelEditCJuridico editCJuridico = new PanelEditCJuridico();
    private PanelEditCNatural editCNatural = new PanelEditCNatural();
    private PanelRegistroLecturaCN registroLecturaCN = new PanelRegistroLecturaCN();
    private PanelRegistroLecturaCJ registroLecturaCJ = new PanelRegistroLecturaCJ();
    private PanelLecturas lecturasTotales = new PanelLecturas();
    private PanelCNServicio cNServicio = new PanelCNServicio();
    private PanelCJServicio cJServicio = new PanelCJServicio();
    
    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        PANEL_MAIN.add(panelMain, Navigation.PANEL_MAIN);
        PANEL_MAIN.add(dataCNatural, Navigation.DATACNatural);
        PANEL_MAIN.add(dataCJuridicos, Navigation.DATACJuridicos);
        PANEL_MAIN.add(registroCNatural, Navigation.REGISTROCNatural);
        PANEL_MAIN.add(registroJuridico, Navigation.REGISTROJuridico);
        PANEL_MAIN.add(editCJuridico, Navigation.EDITJuridico);
        PANEL_MAIN.add(editCNatural, Navigation.EDITNatural);
        PANEL_MAIN.add(registroLecturaCN, Navigation.REGISTRO_LECTURA_CN);
        PANEL_MAIN.add(registroLecturaCJ, Navigation.REGISTRO_LECTURA_CJ);
        PANEL_MAIN.add(lecturasTotales, Navigation.LECTURAS);
        PANEL_MAIN.add(cNServicio, Navigation.SERVICIO_CN);
        PANEL_MAIN.add(cJServicio, Navigation.SERVICIO_CJ);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL_MAIN = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANEL_MAIN.setLayout(new java.awt.CardLayout());
        getContentPane().add(PANEL_MAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Navigation.toPanel(Navigation.PANEL_MAIN);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PANEL_MAIN;
    // End of variables declaration//GEN-END:variables
}
