/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.presentation;

import business.model.*;
import framework.datasource.FileClientes;
import business.interactors.implementation.*;
import util.Navigation;

/**
 *
 * @author GEORGE
 */
public class PanelRegistroLecturaCN extends javax.swing.JPanel {

    private ClienteNatural cn;
    
    /**
     * Creates new form PanelRegistroLecturaM
     */
    public PanelRegistroLecturaCN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_consumo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbox_mes = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Registrar Lectura del Medidor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jLabel2.setText("<html><center>Codigo del<br> Cliente Natural</center></html>");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));

        txt_codigo.setEnabled(false);
        add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, -1));

        jLabel3.setText("<html>Consumo<br> en KW/h<html>");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        add(txt_consumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, -1));

        jLabel4.setText("Mes");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        cbox_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        add(cbox_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setText("<html><center>Registrar<br> Lectura del Mes<center></html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Navigation.toPanel(Navigation.PANEL_MAIN);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            int index = ClientesViewModel.getIndexEdit();
            
            cn = FileClientes.getClienteNatural(index);
            
            txt_codigo.setText(String.valueOf(cn.getCodigo()));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        
        LecturaMedidor lectura = new LecturaMedidor(cn.getCodigo(),
                Float.parseFloat(txt_consumo.getText()) ,
                cbox_mes.getSelectedIndex()+1, 
                cn.precioAPagar(Float.parseFloat(txt_consumo.getText())));
        
        LecturaMedidorViewModel.agregarLectura(lectura);
        
        txt_codigo.setText(null);
        txt_consumo.setText(null);
        
        Navigation.toPanel(Navigation.PANEL_MAIN);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbox_mes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_consumo;
    // End of variables declaration//GEN-END:variables
}
