/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.presentation;

import business.model.*;
import business.interactors.implementation.ClientesViewModel;
import util.Navigation;

/**
 *
 * @author GEORGE
 */
public class PanelRegistroCNatural extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistroCNatural
     */
    public PanelRegistroCNatural() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        btn_registrarCN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbox_conexion = new javax.swing.JComboBox<>();
        cbox_tarifa = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("REGISTRO CLIENTE NATURAL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jLabel2.setText("DNI");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setText("Codigo");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Apellidos");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Nombres");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel6.setText("Direccion");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txt_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dniActionPerformed(evt);
            }
        });
        add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 130, -1));
        add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, 30));
        add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 30));
        add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 130, -1));
        add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, -1));

        btn_registrarCN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_registrarCN.setText("Registrar");
        btn_registrarCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarCNActionPerformed(evt);
            }
        });
        add(btn_registrarCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 130, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Servicio");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel8.setText("Tarifa");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel9.setText("Conexion");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        cbox_conexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monofasico", "Bifasico", "Trifasico" }));
        add(cbox_conexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        cbox_tarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residencial", "Comercial", "Industrial", "Especial" }));
        add(cbox_tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Navigation.toPanel(Navigation.PANEL_MAIN);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_registrarCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarCNActionPerformed
        int codigo = Integer.parseInt(txt_codigo.getText());
        String apellidos = txt_apellidos.getText();
        String nombres = txt_nombres.getText();
        String direccion = txt_direccion.getText();
        String dni = txt_dni.getText();
        
        ClienteNatural cn = new ClienteNatural(
                codigo, 
                apellidos,
                nombres, 
                direccion, 
                dni);
        
        
        
        txt_codigo.setText(null);
        txt_apellidos.setText(null);
        txt_nombres.setText(null);
        txt_direccion.setText(null);
        txt_dni.setText(null);
        
        try {
            switch(cbox_conexion.getSelectedIndex()) {
            case 0: cn.setConexion(ClienteNatural.MONOFASICO);break;
            case 1: cn.setConexion(ClienteNatural.BIFASICO);break;
            case 2: cn.setConexion(ClienteNatural.TRIFASICO);break;
            }
        } catch (Exception e) {
        }
        
        try {
            switch(cbox_tarifa.getSelectedIndex()) {
                case 0: cn.setTarifa(ClienteNatural.RESIDENCIAL);break;
                case 1: cn.setTarifa(ClienteNatural.COMERCIAL);break;
                case 2: cn.setTarifa(ClienteNatural.INDUSTRIAL);break;
                case 3: cn.setTarifa(ClienteNatural.ESPECIAL);break;
            }
        } catch (Exception e) {
        }
        
        ClientesViewModel.agregarClienteNatural(cn);
    }//GEN-LAST:event_btn_registrarCNActionPerformed

    private void txt_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrarCN;
    private javax.swing.JComboBox<String> cbox_conexion;
    private javax.swing.JComboBox<String> cbox_tarifa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_nombres;
    // End of variables declaration//GEN-END:variables
}
